name: ci

 on:
   push:
     branches:
       - develop
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./backend
            -   run: npm install --prefix ./frontend
            -   run: npm run lint --prefix ./backend
            -   run: npm run lint --prefix ./frontend
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./backend
            -   run: npm install --prefix ./frontend
            -   run: npm run build:local --prefix ./backend
            -   run: npm run build:local --prefix ./frontend
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./frontend
            -   run: npm run test:local --prefix ./frontend
    test-acceptance:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./frontend
            -   run: npm install --prefix ./backend
            -   run: npm run start:local --prefix ./backend &
                env:
                    DB_URL: ${{ secrets.DB_URL_DEV }}
            -   run: npm run start:local --prefix ./frontend &
            -   run: npm run wait-for-serve --prefix ./frontend && npm run e2e --prefix ./frontend
                timeout-minutes: 10
    deploy-develop:
        runs-on: ubuntu-latest
        environment: DEV
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   run: npm install --prefix ./frontend
            -   run: npm install --prefix ./backend
            -   run: npm run build:dev --prefix ./backend
            -   run: npm run build:dev --prefix ./frontend
            -   uses: amondnet/vercel-action@v20.0.1
                with:
                    vercel-token: ${{ secrets.VERCEL_TOKEN_DEV }}
                    vercel-org-id: ${{ secrets.VERCEL_ORG_ID_DEV }}
                    vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DEV }
                    vercel-args: --confirm --prod
                    working-directory: ./
