name: ci-dev

on:
  push:
      branches-ignore:
          - master
          - develop

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./backend
            -   run: yarn install --prefix ./frontend
            -   run: npm run lint --prefix ./backend
            -   run: npm run lint --prefix ./frontend
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./backend
            -   run: yarn install --prefix ./frontend
            -   run: npm run build:local --prefix ./backend
            -   run: npm run build:local --prefix ./frontend
    test-unit:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: yarn install --prefix ./frontend
            -   run: npm install --prefix ./backend
            -   run: npm run test:local --prefix ./frontend
            -   run: npm run test:local --prefix ./backend
                env:
                    DB_URL: ${{ secrets.DB_URL }}
    test-acceptance:
        runs-on: ubuntu-latest
        environment: FEATURE
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: yarn install --prefix ./frontend
            -   run: npm install --prefix ./backend
            -   run: npm run start:local --prefix ./backend &
                env:
                    DB_URL: ${{ secrets.DB_URL }}
            -   run: npm run start:local --prefix ./frontend &
            -   run: npm run e2e:local --prefix ./frontend
                timeout-minutes: 10
