name: ci-stage

on:
    push:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./backend
            -   run: npm install --prefix ./frontend
            -   run: npm run lint --prefix ./backend
            -   run: npm run lint --prefix ./frontend
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./backend
            -   run: npm install --prefix ./frontend
            -   run: npm run build:stage --prefix ./backend
            -   run: npm run build:stage --prefix ./frontend
            -   uses: actions/upload-artifact@v3
                with:
                    name: build-backend
                    path: ./backend/build
            -   uses: actions/upload-artifact@v3
                with:
                    name: build-frontend
                    path: ./frontend/dist/frontend
    test-unit:
        runs-on: ubuntu-latest
        environment: STAGE
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./frontend
            -   run: npm install --prefix ./backend
            -   run: npm run test --prefix ./frontend
            -   run: npm run test:local --prefix ./backend
                env:
                    DB_URL: ${{ secrets.DB_URL }}
    test-acceptance:
        runs-on: ubuntu-latest
        environment: STAGE
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./frontend
            -   run: npm install --prefix ./backend
            -   run: npm run start:local --prefix ./backend &
                env:
                    DB_URL: ${{ secrets.DB_URL }}
            -   run: npm run start:local --prefix ./frontend &
            -   run: npm run wait-for-serve --prefix ./frontend && npm run e2e:local --prefix ./frontend
                timeout-minutes: 10
    deploy:
        runs-on: ubuntu-latest
        environment: STAGE
        needs: [ lint, build, test-unit, test-acceptance ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   uses: actions/download-artifact@v3
                with:
                    name: build-backend
                    path: ./backend/build
            -   uses: actions/download-artifact@v3
                with:
                    name: build-frontend
                    path: ./frontend/dist/frontend
            -   uses: amondnet/vercel-action@v20.0.1
                with:
                    vercel-token: ${{ secrets.VERCEL_TOKEN }}
                    vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                    vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                    vercel-args: --confirm --prod
                    working-directory: ./
    test-smoke:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Node 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   run: npm install --prefix ./frontend
            -   run: npm run e2e:stage --prefix ./frontend
                timeout-minutes: 10
