name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Set up Node 14
     uses: actions/setup-node@v1
     with:
      node-version: 14
   - run: npm install --prefix ./backend/
   - run: npm run lint --prefix ./backend/
   - run: npm install --prefix ./frontend/
   - run: npm run lint --prefix ./frontend/
 build:
     runs-on: ubuntu-latest
     steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Set up Node 14
           uses: actions/setup-node@v1
           with:
               node-version: 14
         - run: npm install --prefix ./backend/
         - run: npm run build --prefix ./backend/
         - run: npm install --prefix ./frontend/
         - run: npm run build --prefix ./frontend/
 test:
     runs-on: ubuntu-latest
     strategy:
         matrix:
             node-version: [ 12, 14, 15, 16, 17 ]
     steps:
         -   name: Checkout
             uses: actions/checkout@v2
         -   name: Set up Node ${{ matrix.node-version }}
             uses: actions/setup-node@v1
             with:
                 node-version: ${{ matrix.node-version }}
         -   run: npm install --prefix ./frontend/
         -   run: npm run test --prefix ./frontend/
